/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author bruni
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form telaGenio
     */
    public TelaGenio() {
        initComponents();
        lblFrase.setText("<html> Vou pensar em um valor entre <strong>1</strong> e <strong>5</strong>, tente acertar se for capaz.</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        lblValor = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio pensando.jpg"))); // NOI18N
        getContentPane().add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 524));

        lblFrase.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 200, 170));

        lblValor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lblValorStateChanged(evt);
            }
        });
        lblValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblValorMouseClicked(evt);
            }
        });
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 60, 30));

        btnPalpite.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPalpite.setText("PALPITE");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 100, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("VALOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio pensando.jpg")));
        double n = 1 + Math.random() *(6-1);
        int valor = (int) n;
        
        int num = Integer.parseInt(lblValor.getValue().toString());
        if(valor == num ){
            lblFrase.setText("Droga você acertou!!");
            lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio normal.jpg")));
        }else{
            lblFrase.setText("<html>Eu Acertei, você errou!! hahaha mude o valor </html>");
            lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Génio.png")));
        }
    }//GEN-LAST:event_btnPalpiteActionPerformed

    private void lblValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblValorMouseClicked
      
        
    }//GEN-LAST:event_lblValorMouseClicked

    private void lblValorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lblValorStateChanged
         lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio pensando.jpg")));
        lblFrase.setText("<html> Vi que você mudou o valor, vamos lá .</html>");
    }//GEN-LAST:event_lblValorStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JSpinner lblValor;
    // End of variables declaration//GEN-END:variables
}
